### ISSUE TITLE
Windows-support for `fetch-native-lwt`

### ISSUE THREAD

**Issue by lessp** [lessp/fetch#14]
Is this what you were seeing as well @ulrikstrid? `@opam/conf-openssl`

Found these, could be related:

https://github.com/ocaml/opam-repository/issues/12876
https://github.com/ocaml/opam-repository/issues/13636

_Originally posted by @lessp in https://github.com/lessp/reason-fetch/pull/13#issuecomment-536402184_

**Comment by ulrikstrid** [comment]
Looks like we might just need a override in the esy-opam-override repo, I'll look into this

**Comment by lessp** [comment]
Does the example run for you on Windows @Et7f3? Could it be that `pkg-config` is not available in the CI?

**Comment by Et7f3** [comment]
The package `openssl` isn't installed with esy-bash so neither `pkg-config` nor `x86_64-w64-mingw32-pkg-config` can not find it. And tls failwith `Fatal error: exception (Failure "Nocrypto_entropy_unix: no random device")`  but we can build it.

**Comment by ulrikstrid** [comment]
`"@opam/conf-libssl": "esy-packages/esy-openssl:package.json#860ad7fdce781ad1c1c9349420004d49100178af"` in resolutions should work for `@opam/ssl`.
But httpaf doesn't support Windows until there is a change to Lwt so might be worth it to switch to cohttp.

**Comment by lessp** [comment]
Fixed in #18, thanks @ulrikstrid! ❤️
